### ISSUE TITLE
Using the !card and !showcard commands in setences

### ISSUE THREAD

**Issue by VisofSer** [Zero-to-Heroes/discord-bot#5]
Could the !card and !showcard commands be set to work inside of a sentence as well as on separate lines please?
 As an example I tried to type "C'thun decks get a lot better with cards like:
!showcard twilight elder" earlier today which was not recognised. 

Cheers

**Comment by sebastientromp** [comment]
Fixed with 4b57c17cf80ab5b92adfe94ec905789b3f58df07
